pipeline {
triggers { pollSCM('* * * * *') } // This cron is indicates checking commit update interval(gitteki commitleri algılama taraması sıklığı)
environment {
registry = "anilkuscu95/restarter"
registryCredential = 'dockerhub'
dockerImage = ''
}
agent any
stages {
stage('Cloning our Git') {
steps {
git 'https://github.com/anilkusc/kubernetes-pod-restarter.git'
}
}
stage('Building our image') {
steps{
script {
dockerImage = docker.build registry + ":$BUILD_NUMBER"
}
}
}
stage('Deploy our image') {
steps{
script {
docker.withRegistry( '', registryCredential ) {
dockerImage.push()
}
}
}
}
stage('Cleaning up') {
steps{
sh "docker rmi $registry:$BUILD_NUMBER"
}
}
}
}