apiVersion: v1
kind: Service
metadata:
  name: zentao
  labels:
    app: zentao
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: zentao
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zentao
  labels:
    app: zentao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zentao
  template:
    metadata:
      labels:
        app: zentao
    spec:
      containers:
      - name: zentao
        image: idoop/zentao
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "Europe/Istanbul"
        - name: USER
          value: "root"
        - name: PASSWD
          value: "password"
        - name: BIND_ADDRESS
          value: "false"        
        ports:
          - name: http
            containerPort: 80
          - name: mysql
            containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /opt/zbox/ 
      volumes:
        - name: data
          hostPath:
            path: /volumes/zentao/          
##############default id:admin  default password:123456