apiVersion: v1
kind: Service
metadata:
  name: operator
  labels:
    app: operator
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    app: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - name: operator
        image: 192.168.1.50:30014/operator
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: regcred  